backend:
  name: github
  repo: totoro-hust/myblog
  branch: main
  base_url: https://blog.luckdove.com
  auth_endpoint: api/auth
  auth_type: implicit  # ← 这一行是关键！
  #auth_type: pkce
  #auth_endpoint: https://blog.luckdove.com/api/auth
  #auth_type: pkce
  #app_id: Ov23liye66Qap1bVJKjp

site_url: https://blog.luckdove.com
display_url: https://blog.luckdove.com
locale: zh_Hans

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: posts
    label: 文章
    folder: posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 标题, name: title, widget: string }
      - { label: 发布日期, name: date, widget: datetime, date_format: "YYYY-MM-DD", time_format: false }
      - { label: 标签, name: tags, widget: list, required: false }
      - { label: 分类, name: categories, widget: list, required: false }
      - { label: 封面图, name: cover, widget: image, required: false }
      - { label: 摘要, name: summary, widget: text, required: false }
      - { label: 正文, name: body, widget: markdown }
